#!/usr/bin/env npx tsx
/**
 * Merge Intlayer dictionaries into i18next locale files.
 *
 * This script reads the dictionary JSON files generated by Intlayer
 * (in .intlayer/dictionary/) and transforms them into single locale
 * files (e.g., ./src/locales/en.json) that i18next expects.
 *
 * Usage:
 *   npx tsx scripts/merge-locales.ts
 *
 * Or via npm script:
 *   npm run locales:merge
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const LOCALES = ['en', 'pt', 'es', 'de', 'fr', 'it'];
const DICTIONARY_DIR = path.join(__dirname, '../.intlayer/dictionary');
const OUTPUT_DIR = path.join(__dirname, '../src/locales');

interface IntlayerDictionary {
  key: string;
  content: {
    nodeType: string;
    translation: Record<string, Record<string, string>>;
  };
}

function extractTranslations(content: unknown): Record<string, string> | null {
  if (!content || typeof content !== 'object') {
    return null;
  }

  const obj = content as Record<string, unknown>;

  // If it's a translation node, extract translations for the locale
  if (obj.nodeType === 'translation' && obj.translation) {
    return null; // This is handled at a higher level
  }

  return null;
}

function flattenTranslations(
  content: Record<string, unknown>,
  locale: string
): Record<string, string> {
  const result: Record<string, string> = {};

  // The content.translation contains all locales
  if (content.nodeType === 'translation' && content.translation) {
    const translations = content.translation as Record<string, Record<string, string>>;
    if (translations[locale]) {
      return translations[locale];
    }
  }

  return result;
}

function mergeLocales(): void {
  console.log('Merging Intlayer dictionaries into i18next locale files...\n');

  // Check if dictionary directory exists
  if (!fs.existsSync(DICTIONARY_DIR)) {
    console.error(`[ERROR] Dictionary directory not found: ${DICTIONARY_DIR}`);
    console.error('Run "npm run intlayer:build" first to generate dictionaries.');
    process.exit(1);
  }

  // Read all dictionary files
  const dictionaryFiles = fs.readdirSync(DICTIONARY_DIR).filter(f => f.endsWith('.json'));

  if (dictionaryFiles.length === 0) {
    console.error('[ERROR] No dictionary files found.');
    process.exit(1);
  }

  console.log(`Found ${dictionaryFiles.length} dictionaries: ${dictionaryFiles.map(f => f.replace('.json', '')).join(', ')}\n`);

  // Load all dictionaries
  const dictionaries: IntlayerDictionary[] = [];
  for (const file of dictionaryFiles) {
    try {
      const content = JSON.parse(fs.readFileSync(path.join(DICTIONARY_DIR, file), 'utf-8'));
      dictionaries.push(content);
    } catch (error) {
      console.error(`[ERROR] Failed to parse ${file}:`, error);
    }
  }

  // Create merged files for each locale
  for (const locale of LOCALES) {
    const merged: Record<string, Record<string, string>> = {};

    for (const dict of dictionaries) {
      const namespace = dict.key;
      const translations = flattenTranslations(dict.content, locale);

      if (Object.keys(translations).length > 0) {
        merged[namespace] = translations;
      }
    }

    // Write merged file
    const outputFile = path.join(OUTPUT_DIR, `${locale}.json`);
    fs.writeFileSync(outputFile, JSON.stringify(merged, null, 2) + '\n');
    console.log(`  [OK] ${locale}.json: ${Object.keys(merged).length} namespaces`);
  }

  console.log('\nDone!');
}

// Run if called directly
mergeLocales();
