import { t, type Dictionary } from 'intlayer';

/**
 * Assessment translations
 * Risk assessment workflow and questionnaire labels
 */
const assessmentContent = {
  key: 'assessment',
  content: {
    title: t({
      en: 'Risk Assessment',
      pt: 'Avaliação de Risco',
      es: 'Evaluación de Riesgo',
      de: 'Risikobewertung',
      fr: 'Évaluation des risques',
      it: 'Valutazione del rischio',
    }),
    startAssessment: t({
      en: 'Start Assessment',
      pt: 'Iniciar Avaliação',
      es: 'Iniciar Evaluación',
      de: 'Bewertung starten',
      fr: "Démarrer l'évaluation",
      it: 'Inizia valutazione',
    }),
    continueAssessment: t({
      en: 'Continue Assessment',
      pt: 'Continuar Avaliação',
      es: 'Continuar Evaluación',
      de: 'Bewertung fortsetzen',
      fr: "Continuer l'évaluation",
      it: 'Continua valutazione',
    }),
    viewAssessment: t({
      en: 'View Assessment',
      pt: 'Ver Avaliação',
      es: 'Ver Evaluación',
      de: 'Bewertung ansehen',
      fr: "Voir l'évaluation",
      it: 'Visualizza valutazione',
    }),
    preliminaryClassification: t({
      en: 'Preliminary Classification',
      pt: 'Classificação Preliminar',
      es: 'Clasificación Preliminar',
      de: 'Vorläufige Klassifizierung',
      fr: 'Classification préliminaire',
      it: 'Classificazione preliminare',
    }),
    finalClassification: t({
      en: 'Final Classification',
      pt: 'Classificação Final',
      es: 'Clasificación Final',
      de: 'Endgültige Klassifizierung',
      fr: 'Classification finale',
      it: 'Classificazione finale',
    }),
    justification: t({
      en: 'Justification',
      pt: 'Justificativa',
      es: 'Justificación',
      de: 'Begründung',
      fr: 'Justification',
      it: 'Giustificazione',
    }),
    assessmentStatus: t({
      en: 'Assessment Status',
      pt: 'Status da Avaliação',
      es: 'Estado de la Evaluación',
      de: 'Bewertungsstatus',
      fr: "Statut de l'évaluation",
      it: 'Stato della valutazione',
    }),
    pending: t({
      en: 'Pending',
      pt: 'Pendente',
      es: 'Pendiente',
      de: 'Ausstehend',
      fr: 'En attente',
      it: 'In sospeso',
    }),
    inProgress: t({
      en: 'In Progress',
      pt: 'Em Andamento',
      es: 'En Progreso',
      de: 'In Bearbeitung',
      fr: 'En cours',
      it: 'In corso',
    }),
    completed: t({
      en: 'Completed',
      pt: 'Concluída',
      es: 'Completada',
      de: 'Abgeschlossen',
      fr: 'Terminé',
      it: 'Completata',
    }),
    questionnaireTitle: t({
      en: 'Assessment Questionnaire',
      pt: 'Questionário de Avaliação',
      es: 'Cuestionario de Evaluación',
      de: 'Bewertungsfragebogen',
      fr: "Questionnaire d'évaluation",
      it: 'Questionario di valutazione',
    }),
    category: t({
      en: 'Category',
      pt: 'Categoria',
      es: 'Categoría',
      de: 'Kategorie',
      fr: 'Catégorie',
      it: 'Categoria',
    }),
    question: t({
      en: 'Question',
      pt: 'Pergunta',
      es: 'Pregunta',
      de: 'Frage',
      fr: 'Question',
      it: 'Domanda',
    }),
    answer: t({
      en: 'Answer',
      pt: 'Resposta',
      es: 'Respuesta',
      de: 'Antwort',
      fr: 'Réponse',
      it: 'Risposta',
    }),
    helpText: t({
      en: 'Help',
      pt: 'Ajuda',
      es: 'Ayuda',
      de: 'Hilfe',
      fr: 'Aide',
      it: 'Aiuto',
    }),
    noAssessments: t({
      en: 'No assessments found',
      pt: 'Nenhuma avaliação encontrada',
      es: 'No se encontraron evaluaciones',
      de: 'Keine Bewertungen gefunden',
      fr: 'Aucune évaluation trouvée',
      it: 'Nessuna valutazione trovata',
    }),
    completeAssessment: t({
      en: 'Complete Assessment',
      pt: 'Concluir Avaliação',
      es: 'Completar Evaluación',
      de: 'Bewertung abschließen',
      fr: "Terminer l'évaluation",
      it: 'Completa valutazione',
    }),
    assessmentComplete: t({
      en: 'Assessment completed successfully',
      pt: 'Avaliação concluída com sucesso',
      es: 'Evaluación completada exitosamente',
      de: 'Bewertung erfolgreich abgeschlossen',
      fr: 'Évaluation terminée avec succès',
      it: 'Valutazione completata con successo',
    }),
  },
} satisfies Dictionary;

export default assessmentContent;
