import { t, type Dictionary } from 'intlayer';

/**
 * Authentication translations
 * Login, registration, and password reset related strings
 */
const authContent = {
  key: 'auth',
  content: {
    login: t({
      en: 'Login',
      pt: 'Entrar',
      es: 'Iniciar sesión',
      de: 'Anmelden',
      fr: 'Connexion',
      it: 'Accedi',
    }),
    register: t({
      en: 'Register',
      pt: 'Registrar',
      es: 'Registrarse',
      de: 'Registrieren',
      fr: "S'inscrire",
      it: 'Registrati',
    }),
    email: t({
      en: 'Email',
      pt: 'E-mail',
      es: 'Correo electrónico',
      de: 'E-Mail',
      fr: 'E-mail',
      it: 'E-mail',
    }),
    password: t({
      en: 'Password',
      pt: 'Senha',
      es: 'Contraseña',
      de: 'Passwort',
      fr: 'Mot de passe',
      it: 'Password',
    }),
    confirmPassword: t({
      en: 'Confirm Password',
      pt: 'Confirmar Senha',
      es: 'Confirmar contraseña',
      de: 'Passwort bestätigen',
      fr: 'Confirmer le mot de passe',
      it: 'Conferma password',
    }),
    name: t({
      en: 'Full Name',
      pt: 'Nome Completo',
      es: 'Nombre completo',
      de: 'Vollständiger Name',
      fr: 'Nom complet',
      it: 'Nome completo',
    }),
    organization: t({
      en: 'Organization',
      pt: 'Organização',
      es: 'Organización',
      de: 'Organisation',
      fr: 'Organisation',
      it: 'Organizzazione',
    }),
    forgotPassword: t({
      en: 'Forgot Password?',
      pt: 'Esqueceu a senha?',
      es: '¿Olvidaste tu contraseña?',
      de: 'Passwort vergessen?',
      fr: 'Mot de passe oublié?',
      it: 'Password dimenticata?',
    }),
    resetPassword: t({
      en: 'Reset Password',
      pt: 'Redefinir Senha',
      es: 'Restablecer contraseña',
      de: 'Passwort zurücksetzen',
      fr: 'Réinitialiser le mot de passe',
      it: 'Reimposta password',
    }),
    loginSuccess: t({
      en: 'Login successful',
      pt: 'Login realizado com sucesso',
      es: 'Inicio de sesión exitoso',
      de: 'Anmeldung erfolgreich',
      fr: 'Connexion réussie',
      it: 'Accesso riuscito',
    }),
    registerSuccess: t({
      en: 'Registration successful',
      pt: 'Registro realizado com sucesso',
      es: 'Registro exitoso',
      de: 'Registrierung erfolgreich',
      fr: 'Inscription réussie',
      it: 'Registrazione riuscita',
    }),
    logoutSuccess: t({
      en: 'Logout successful',
      pt: 'Logout realizado com sucesso',
      es: 'Cierre de sesión exitoso',
      de: 'Abmeldung erfolgreich',
      fr: 'Déconnexion réussie',
      it: 'Disconnessione riuscita',
    }),
    invalidCredentials: t({
      en: 'Invalid email or password',
      pt: 'E-mail ou senha inválidos',
      es: 'Correo electrónico o contraseña inválidos',
      de: 'Ungültige E-Mail oder Passwort',
      fr: 'E-mail ou mot de passe invalide',
      it: 'E-mail o password non validi',
    }),
    emailExists: t({
      en: 'Email already registered',
      pt: 'E-mail já registrado',
      es: 'Correo electrónico ya registrado',
      de: 'E-Mail bereits registriert',
      fr: 'E-mail déjà enregistré',
      it: 'E-mail già registrata',
    }),
    passwordMismatch: t({
      en: 'Passwords do not match',
      pt: 'As senhas não coincidem',
      es: 'Las contraseñas no coinciden',
      de: 'Passwörter stimmen nicht überein',
      fr: 'Les mots de passe ne correspondent pas',
      it: 'Le password non corrispondono',
    }),
    resetEmailSent: t({
      en: 'Password reset email sent',
      pt: 'E-mail de redefinição enviado',
      es: 'Correo de restablecimiento enviado',
      de: 'E-Mail zum Zurücksetzen des Passworts gesendet',
      fr: 'E-mail de réinitialisation envoyé',
      it: 'E-mail di reimpostazione inviata',
    }),
    noAccount: t({
      en: "Don't have an account?",
      pt: 'Não tem uma conta?',
      es: '¿No tienes una cuenta?',
      de: 'Noch kein Konto?',
      fr: "Vous n'avez pas de compte?",
      it: 'Non hai un account?',
    }),
    hasAccount: t({
      en: 'Already have an account?',
      pt: 'Já tem uma conta?',
      es: '¿Ya tienes una cuenta?',
      de: 'Bereits ein Konto?',
      fr: 'Vous avez déjà un compte?',
      it: 'Hai già un account?',
    }),
  },
} satisfies Dictionary;

export default authContent;
