import { t, type Dictionary } from 'intlayer';

/**
 * Common translations used across the application
 * These include general UI elements, buttons, and messages
 */
const commonContent = {
  key: 'common',
  content: {
    appName: t({
      en: 'EU AI Act Compliance Platform',
      pt: 'Plataforma de Conformidade EU AI Act',
      es: 'Plataforma de Cumplimiento EU AI Act',
      de: 'EU-KI-Gesetz Compliance-Plattform',
      fr: 'Plateforme de Conformité EU AI Act',
      it: 'Piattaforma di Conformità EU AI Act',
    }),
    welcome: t({
      en: 'Welcome',
      pt: 'Bem-vindo',
      es: 'Bienvenido',
      de: 'Willkommen',
      fr: 'Bienvenue',
      it: 'Benvenuto',
    }),
    logout: t({
      en: 'Logout',
      pt: 'Sair',
      es: 'Cerrar sesión',
      de: 'Abmelden',
      fr: 'Déconnexion',
      it: 'Esci',
    }),
    save: t({
      en: 'Save',
      pt: 'Salvar',
      es: 'Guardar',
      de: 'Speichern',
      fr: 'Enregistrer',
      it: 'Salva',
    }),
    cancel: t({
      en: 'Cancel',
      pt: 'Cancelar',
      es: 'Cancelar',
      de: 'Abbrechen',
      fr: 'Annuler',
      it: 'Annulla',
    }),
    delete: t({
      en: 'Delete',
      pt: 'Excluir',
      es: 'Eliminar',
      de: 'Löschen',
      fr: 'Supprimer',
      it: 'Elimina',
    }),
    edit: t({
      en: 'Edit',
      pt: 'Editar',
      es: 'Editar',
      de: 'Bearbeiten',
      fr: 'Modifier',
      it: 'Modifica',
    }),
    create: t({
      en: 'Create',
      pt: 'Criar',
      es: 'Crear',
      de: 'Erstellen',
      fr: 'Créer',
      it: 'Crea',
    }),
    search: t({
      en: 'Search',
      pt: 'Pesquisar',
      es: 'Buscar',
      de: 'Suchen',
      fr: 'Rechercher',
      it: 'Cerca',
    }),
    loading: t({
      en: 'Loading...',
      pt: 'Carregando...',
      es: 'Cargando...',
      de: 'Laden...',
      fr: 'Chargement...',
      it: 'Caricamento...',
    }),
    error: t({
      en: 'Error',
      pt: 'Erro',
      es: 'Error',
      de: 'Fehler',
      fr: 'Erreur',
      it: 'Errore',
    }),
    success: t({
      en: 'Success',
      pt: 'Sucesso',
      es: 'Éxito',
      de: 'Erfolg',
      fr: 'Succès',
      it: 'Successo',
    }),
    confirm: t({
      en: 'Confirm',
      pt: 'Confirmar',
      es: 'Confirmar',
      de: 'Bestätigen',
      fr: 'Confirmer',
      it: 'Conferma',
    }),
    yes: t({
      en: 'Yes',
      pt: 'Sim',
      es: 'Sí',
      de: 'Ja',
      fr: 'Oui',
      it: 'Sì',
    }),
    no: t({
      en: 'No',
      pt: 'Não',
      es: 'No',
      de: 'Nein',
      fr: 'Non',
      it: 'No',
    }),
    back: t({
      en: 'Back',
      pt: 'Voltar',
      es: 'Volver',
      de: 'Zurück',
      fr: 'Retour',
      it: 'Indietro',
    }),
    next: t({
      en: 'Next',
      pt: 'Próximo',
      es: 'Siguiente',
      de: 'Weiter',
      fr: 'Suivant',
      it: 'Avanti',
    }),
    previous: t({
      en: 'Previous',
      pt: 'Anterior',
      es: 'Anterior',
      de: 'Zurück',
      fr: 'Précédent',
      it: 'Precedente',
    }),
    submit: t({
      en: 'Submit',
      pt: 'Enviar',
      es: 'Enviar',
      de: 'Absenden',
      fr: 'Soumettre',
      it: 'Invia',
    }),
    required: t({
      en: 'Required',
      pt: 'Obrigatório',
      es: 'Obligatorio',
      de: 'Erforderlich',
      fr: 'Requis',
      it: 'Obbligatorio',
    }),
    optional: t({
      en: 'Optional',
      pt: 'Opcional',
      es: 'Opcional',
      de: 'Optional',
      fr: 'Optionnel',
      it: 'Opzionale',
    }),
    actions: t({
      en: 'Actions',
      pt: 'Ações',
      es: 'Acciones',
      de: 'Aktionen',
      fr: 'Actions',
      it: 'Azioni',
    }),
    view: t({
      en: 'View',
      pt: 'Visualizar',
      es: 'Ver',
      de: 'Ansehen',
      fr: 'Voir',
      it: 'Visualizza',
    }),
    noData: t({
      en: 'No data available',
      pt: 'Nenhum dado disponível',
      es: 'No hay datos disponibles',
      de: 'Keine Daten verfügbar',
      fr: 'Aucune donnée disponible',
      it: 'Nessun dato disponibile',
    }),
  },
} satisfies Dictionary;

export default commonContent;
