import { t, type Dictionary } from 'intlayer';

/**
 * AI Systems translations
 * System registration and management labels
 */
const systemsContent = {
  key: 'systems',
  content: {
    title: t({
      en: 'AI Systems',
      pt: 'Sistemas de IA',
      es: 'Sistemas de IA',
      de: 'KI-Systeme',
      fr: 'Systèmes IA',
      it: 'Sistemi IA',
    }),
    createSystem: t({
      en: 'Register New AI System',
      pt: 'Registrar Novo Sistema de IA',
      es: 'Registrar Nuevo Sistema de IA',
      de: 'Neues KI-System registrieren',
      fr: 'Enregistrer un nouveau Système IA',
      it: 'Registra nuovo Sistema IA',
    }),
    editSystem: t({
      en: 'Edit AI System',
      pt: 'Editar Sistema de IA',
      es: 'Editar Sistema de IA',
      de: 'KI-System bearbeiten',
      fr: 'Modifier le Système IA',
      it: 'Modifica Sistema IA',
    }),
    systemName: t({
      en: 'System Name',
      pt: 'Nome do Sistema',
      es: 'Nombre del Sistema',
      de: 'Systemname',
      fr: 'Nom du système',
      it: 'Nome del sistema',
    }),
    description: t({
      en: 'Description',
      pt: 'Descrição',
      es: 'Descripción',
      de: 'Beschreibung',
      fr: 'Description',
      it: 'Descrizione',
    }),
    version: t({
      en: 'Version',
      pt: 'Versão',
      es: 'Versión',
      de: 'Version',
      fr: 'Version',
      it: 'Versione',
    }),
    intendedPurpose: t({
      en: 'Intended Purpose',
      pt: 'Propósito Pretendido',
      es: 'Propósito previsto',
      de: 'Vorgesehener Zweck',
      fr: 'Objectif prévu',
      it: 'Scopo previsto',
    }),
    deploymentContext: t({
      en: 'Deployment Context',
      pt: 'Contexto de Implantação',
      es: 'Contexto de implementación',
      de: 'Einsatzkontext',
      fr: 'Contexte de déploiement',
      it: 'Contesto di distribuzione',
    }),
    aiTechniques: t({
      en: 'AI Techniques Used',
      pt: 'Técnicas de IA Utilizadas',
      es: 'Técnicas de IA utilizadas',
      de: 'Verwendete KI-Techniken',
      fr: "Techniques d'IA utilisées",
      it: 'Tecniche IA utilizzate',
    }),
    riskLevel: t({
      en: 'Risk Level',
      pt: 'Nível de Risco',
      es: 'Nivel de Riesgo',
      de: 'Risikostufe',
      fr: 'Niveau de risque',
      it: 'Livello di rischio',
    }),
    status: t({
      en: 'Status',
      pt: 'Status',
      es: 'Estado',
      de: 'Status',
      fr: 'Statut',
      it: 'Stato',
    }),
    createdAt: t({
      en: 'Created At',
      pt: 'Criado em',
      es: 'Creado el',
      de: 'Erstellt am',
      fr: 'Créé le',
      it: 'Creato il',
    }),
    updatedAt: t({
      en: 'Last Updated',
      pt: 'Última Atualização',
      es: 'Última actualización',
      de: 'Zuletzt aktualisiert',
      fr: 'Dernière mise à jour',
      it: 'Ultimo aggiornamento',
    }),
    noSystems: t({
      en: 'No AI systems registered yet',
      pt: 'Nenhum sistema de IA registrado ainda',
      es: 'No hay sistemas de IA registrados todavía',
      de: 'Noch keine KI-Systeme registriert',
      fr: "Aucun système IA enregistré pour l'instant",
      it: 'Nessun sistema IA registrato ancora',
    }),
    deleteConfirm: t({
      en: 'Are you sure you want to delete this AI system?',
      pt: 'Tem certeza que deseja excluir este sistema de IA?',
      es: '¿Está seguro de que desea eliminar este sistema de IA?',
      de: 'Sind Sie sicher, dass Sie dieses KI-System löschen möchten?',
      fr: 'Êtes-vous sûr de vouloir supprimer ce système IA?',
      it: 'Sei sicuro di voler eliminare questo sistema IA?',
    }),
    createSuccess: t({
      en: 'AI system created successfully',
      pt: 'Sistema de IA criado com sucesso',
      es: 'Sistema de IA creado exitosamente',
      de: 'KI-System erfolgreich erstellt',
      fr: 'Système IA créé avec succès',
      it: 'Sistema IA creato con successo',
    }),
    updateSuccess: t({
      en: 'AI system updated successfully',
      pt: 'Sistema de IA atualizado com sucesso',
      es: 'Sistema de IA actualizado exitosamente',
      de: 'KI-System erfolgreich aktualisiert',
      fr: 'Système IA mis à jour avec succès',
      it: 'Sistema IA aggiornato con successo',
    }),
    deleteSuccess: t({
      en: 'AI system deleted successfully',
      pt: 'Sistema de IA excluído com sucesso',
      es: 'Sistema de IA eliminado exitosamente',
      de: 'KI-System erfolgreich gelöscht',
      fr: 'Système IA supprimé avec succès',
      it: 'Sistema IA eliminato con successo',
    }),
  },
} satisfies Dictionary;

export default systemsContent;
